import type {
  DeploymentDetailRead,
  IncidentCommandCenterRead,
  ProjectReliabilityControlPanel,
  TraceGraphAnalysisRead,
  TraceGraphRead,
} from "@reliai/types";

export const demoProject = {
  id: "proj_demo_reliai",
  name: "Acme Support Agent",
  environment: "production",
};

export const demoControlPanel: ProjectReliabilityControlPanel = {
  reliability_score: 92,
  active_incidents: 1,
  deployment_risk: {
    latest_deployment_id: "dep_demo_v42",
    deployed_at: "2026-03-11T09:00:00Z",
    risk_score: 0.24,
    risk_level: "low",
  },
  simulation: {
    latest_simulation_id: "sim_demo_v42",
    predicted_failure_rate: 0.07,
    predicted_latency: 1280,
    risk_level: "medium",
    created_at: "2026-03-11T08:45:00Z",
  },
  incidents: {
    recent_incidents: [
      {
        incident_id: "inc_demo_latency",
        title: "Retrieval latency regression after prompt rollout",
        severity: "high",
        status: "open",
        started_at: "2026-03-11T10:22:00Z",
      },
    ],
    incident_rate_last_24h: 1,
  },
  guardrails: {
    trigger_rate_last_24h: 17,
    top_triggered_policy: "structured_output",
  },
  guardrail_activity: [
    { policy_type: "structured_output", trigger_count: 11 },
    { policy_type: "latency_retry", trigger_count: 4 },
    { policy_type: "cost_budget", trigger_count: 2 },
  ],
  guardrail_compliance: [
    { policy_type: "structured_output", enforcement_mode: "enforce", coverage_pct: 98, violation_count: 3 },
    { policy_type: "cost_budget", enforcement_mode: "warn", coverage_pct: 96, violation_count: 5 },
    { policy_type: "latency_retry", enforcement_mode: "enforce", coverage_pct: 94, violation_count: 2 },
  ],
  model_reliability: {
    current_model: "gpt-4.1-mini",
    success_rate: 0.982,
    average_latency: 1180,
    structured_output_validity: 0.989,
  },
  high_risk_patterns: [
    { pattern: "Hallucination spike detected", risk_level: "medium", trace_count: 238, confidence: 0.81 },
    { pattern: "Latency regression in retrieval stage", risk_level: "high", trace_count: 142, confidence: 0.88 },
  ],
  graph_high_risk_patterns: [
    { pattern: "Retrieval timeout under long-context prompts", risk_level: "high", trace_count: 142, confidence: 0.88 },
  ],
  recommended_guardrails: [
    {
      policy_type: "structured_output",
      recommended_action: "Enable schema validation and retries",
      title: "Enable structured output validation",
      confidence: 0.91,
      model_family: "gpt-4.1",
    },
    {
      policy_type: "latency_retry",
      recommended_action: "Retry retrieval failures once before fallback",
      title: "Add retry policy for retrieval failures",
      confidence: 0.84,
      model_family: null,
    },
  ],
  model_failure_signals: [
    { pattern: "Tool-call burst after retrieval miss", risk_level: "medium", confidence: 0.72 },
  ],
  recent_deployments: [
    { deployment_id: "dep_demo_v42", deployed_at: "2026-03-11T09:00:00Z", environment: "production", risk_level: "low", risk_score: 0.24 },
  ],
  automatic_actions: {
    recent_actions: [
      {
        action_id: "act_demo_rollback_check",
        action_type: "enable_guardrail",
        target: "structured_output",
        status: "success",
        created_at: "2026-03-11T10:28:00Z",
      },
    ],
  },
};

export const demoTraceGraph: TraceGraphRead = {
  trace_id: "trace_demo_agent_94f3",
  project_id: demoProject.id,
  environment: "production",
  nodes: [
    {
      id: "node_root",
      trace_id: "trace_demo_agent_94f3",
      span_id: "span_root",
      parent_span_id: null,
      span_name: "ai_request",
      span_type: "request",
      model_name: "gpt-4.1-mini",
      model_provider: "openai",
      latency_ms: 2310,
      prompt_tokens: 0,
      completion_tokens: 0,
      success: true,
      guardrail_policy: null,
      guardrail_action: null,
      timestamp: "2026-03-11T10:24:00Z",
      metadata_json: { route: "/chat", customer_tier: "enterprise" },
    },
    {
      id: "node_retrieval",
      trace_id: "trace_demo_agent_94f3",
      span_id: "span_retrieval",
      parent_span_id: "span_root",
      span_name: "retrieve_context",
      span_type: "retrieval",
      model_name: "pgvector",
      model_provider: "internal",
      latency_ms: 980,
      prompt_tokens: 0,
      completion_tokens: 0,
      success: true,
      guardrail_policy: "latency_retry",
      guardrail_action: "retry",
      timestamp: "2026-03-11T10:24:00Z",
      metadata_json: { chunks: 6, query: "refund eligibility for order cancellation" },
    },
    {
      id: "node_prompt",
      trace_id: "trace_demo_agent_94f3",
      span_id: "span_prompt",
      parent_span_id: "span_root",
      span_name: "build_prompt",
      span_type: "prompt_build",
      model_name: "prompt-assembler",
      model_provider: "internal",
      latency_ms: 180,
      prompt_tokens: 3100,
      completion_tokens: 0,
      success: true,
      guardrail_policy: null,
      guardrail_action: null,
      timestamp: "2026-03-11T10:24:01Z",
      metadata_json: { template: "support/refund-v42" },
    },
    {
      id: "node_llm",
      trace_id: "trace_demo_agent_94f3",
      span_id: "span_llm",
      parent_span_id: "span_root",
      span_name: "answer_customer",
      span_type: "llm_call",
      model_name: "gpt-4.1-mini",
      model_provider: "openai",
      latency_ms: 760,
      prompt_tokens: 3100,
      completion_tokens: 740,
      success: true,
      guardrail_policy: "structured_output",
      guardrail_action: "retry",
      timestamp: "2026-03-11T10:24:01Z",
      metadata_json: { temperature: 0.2 },
    },
    {
      id: "node_tool",
      trace_id: "trace_demo_agent_94f3",
      span_id: "span_tool",
      parent_span_id: "span_llm",
      span_name: "lookup_order_status",
      span_type: "tool_call",
      model_name: "order-service",
      model_provider: "internal",
      latency_ms: 240,
      prompt_tokens: 0,
      completion_tokens: 0,
      success: true,
      guardrail_policy: null,
      guardrail_action: null,
      timestamp: "2026-03-11T10:24:02Z",
      metadata_json: { dependency: "orders-api" },
    },
    {
      id: "node_postprocess",
      trace_id: "trace_demo_agent_94f3",
      span_id: "span_post",
      parent_span_id: "span_root",
      span_name: "postprocess_answer",
      span_type: "postprocess",
      model_name: "response-normalizer",
      model_provider: "internal",
      latency_ms: 150,
      prompt_tokens: 0,
      completion_tokens: 0,
      success: true,
      guardrail_policy: null,
      guardrail_action: null,
      timestamp: "2026-03-11T10:24:03Z",
      metadata_json: { schema: "ticket_resolution_v3" },
    },
  ],
  edges: [
    { parent_span_id: "span_root", child_span_id: "span_retrieval" },
    { parent_span_id: "span_root", child_span_id: "span_prompt" },
    { parent_span_id: "span_root", child_span_id: "span_llm" },
    { parent_span_id: "span_llm", child_span_id: "span_tool" },
    { parent_span_id: "span_root", child_span_id: "span_post" },
  ],
};

export const demoTraceAnalysis: TraceGraphAnalysisRead = {
  trace_id: demoTraceGraph.trace_id,
  slowest_span: {
    span_id: "span_retrieval",
    span_name: "retrieve_context",
    span_type: "retrieval",
    latency_ms: 980,
    token_count: null,
    guardrail_policy: "latency_retry",
    retry_count: 1,
  },
  largest_token_span: {
    span_id: "span_llm",
    span_name: "answer_customer",
    span_type: "llm_call",
    latency_ms: 760,
    token_count: 3840,
    guardrail_policy: "structured_output",
    retry_count: 1,
  },
  most_guardrail_retries: {
    span_id: "span_llm",
    span_name: "answer_customer",
    span_type: "llm_call",
    latency_ms: 760,
    token_count: 3840,
    guardrail_policy: "structured_output",
    retry_count: 1,
  },
};

export const demoIncidentCommand: IncidentCommandCenterRead = {
  incident: {
    id: "inc_demo_latency",
    organization_id: "org_demo",
    project_id: demoProject.id,
    environment_id: "env_demo_prod",
    project_name: demoProject.name,
    incident_type: "latency_regression",
    severity: "high",
    title: "Retrieval latency regression after prompt rollout",
    status: "open",
    fingerprint: "latency_regression:retrieval",
    summary_json: {
      metric_name: "retrieval_latency_ms",
      scope_type: "environment",
      scope_id: "production",
      window_minutes: 30,
    },
    started_at: "2026-03-11T10:22:00Z",
    updated_at: "2026-03-11T10:29:00Z",
    resolved_at: null,
    acknowledged_at: "2026-03-11T10:25:00Z",
    acknowledged_by_operator_user_id: "user_demo",
    acknowledged_by_operator_email: "owner@acme.test",
    owner_operator_user_id: "user_demo",
    owner_operator_email: "owner@acme.test",
    latest_alert_delivery: null,
    regressions: [],
    traces: [
      {
        id: "trace_demo_agent_94f3",
        request_id: "req_94f3",
        timestamp: "2026-03-11T10:24:00Z",
        success: true,
        error_type: null,
        latency_ms: 2310,
        total_cost_usd: "0.0142",
      },
    ],
    events: [],
    deployment_context: {
      deployment: {
        id: "dep_demo_v42",
        project_id: demoProject.id,
        environment_id: "env_demo_prod",
        prompt_version_id: "prompt_v42",
        model_version_id: "model_gpt41mini_v8",
        environment: "production",
        deployed_by: "release-bot@acme.test",
        deployed_at: "2026-03-11T09:00:00Z",
        metadata_json: { release_channel: "progressive" },
        created_at: "2026-03-11T09:00:00Z",
      },
      prompt_version: {
        id: "prompt_v42",
        project_id: demoProject.id,
        version: "support/refund-v42",
        created_at: "2026-03-10T17:00:00Z",
        updated_at: "2026-03-10T17:00:00Z",
        label: "Refund support prompt",
        notes: "Expanded retrieval context from 4 to 6 chunks.",
      },
      model_version: {
        id: "model_gpt41mini_v8",
        project_id: demoProject.id,
        provider: "openai",
        model_name: "gpt-4.1-mini",
        model_version: "2026-03-08",
        model_family: "gpt-4.1",
        model_revision: "mini",
        route_key: "prod-stable",
        label: "Support stable",
        identity_key: "openai:gpt-4.1-mini:2026-03-08",
        created_at: "2026-03-08T12:00:00Z",
        updated_at: "2026-03-08T12:00:00Z",
      },
      time_since_deployment_minutes: 82,
    },
    compare: {
      current_window_start: "2026-03-11T10:00:00Z",
      current_window_end: "2026-03-11T10:30:00Z",
      baseline_window_start: "2026-03-11T09:00:00Z",
      baseline_window_end: "2026-03-11T09:30:00Z",
      regressions: [],
      representative_traces: [],
      current_representative_traces: [],
      baseline_representative_traces: [],
      root_cause_hints: [],
      dimension_summaries: [],
      prompt_version_contexts: [],
      model_version_contexts: [],
      cohort_pivots: [],
      rule_context: null,
      trace_compare_path: "/compare/incident-demo",
    },
  },
  root_cause: {
    incident_id: "inc_demo_latency",
    generated_at: "2026-03-11T10:29:00Z",
    root_cause_probabilities: [
      {
        cause_type: "deployment_change",
        label: "Prompt rollout changed retrieval behavior",
        probability: 0.71,
        evidence_json: { prompt_version_id: "prompt_v42" },
      },
      {
        cause_type: "retrieval_latency",
        label: "Retrieval stage is exceeding expected latency",
        probability: 0.62,
        evidence_json: { p95_latency_ms: 980 },
      },
      {
        cause_type: "global_pattern",
        label: "Similar long-context retrieval failures seen elsewhere",
        probability: 0.48,
        evidence_json: { pattern: "long context retrieval timeout" },
      },
    ],
    evidence: {},
    recommended_fix: {
      fix_type: "guardrail",
      summary: "Enable latency retry on retrieval and compare v42 against the previous prompt before expanding rollout.",
      metadata_json: null,
    },
  },
  trace_compare: {
    failing_trace_summary: {
      id: "trace_current",
      request_id: "req_94f3",
      timestamp: "2026-03-11T10:24:00Z",
      model_name: "gpt-4.1-mini",
      prompt_version: "support/refund-v42",
      success: true,
      error_type: null,
      latency_ms: 2310,
      prompt_tokens: 3100,
      completion_tokens: 740,
      total_cost_usd: "0.0142",
      prompt_version_record: null,
      model_version_record: null,
      structured_output: { label: "pass", score: "0.98", reason: "Schema valid after one retry" },
      retrieval: { retrieval_latency_ms: 980, source_count: 6, top_k: 6 },
      metadata_excerpt_json: { region: "us-east-1" },
    },
    baseline_trace_summary: {
      id: "trace_baseline",
      request_id: "req_8201",
      timestamp: "2026-03-11T09:14:00Z",
      model_name: "gpt-4.1-mini",
      prompt_version: "support/refund-v41",
      success: true,
      error_type: null,
      latency_ms: 1480,
      prompt_tokens: 2780,
      completion_tokens: 620,
      total_cost_usd: "0.0108",
      prompt_version_record: null,
      model_version_record: null,
      structured_output: { label: "pass", score: "0.99", reason: "Schema valid" },
      retrieval: { retrieval_latency_ms: 410, source_count: 4, top_k: 4 },
      metadata_excerpt_json: { region: "us-east-1" },
    },
    compare_link: "/compare/incident-demo",
  },
  deployment_context: {
    deployment: {
      id: "dep_demo_v42",
      project_id: demoProject.id,
      environment_id: "env_demo_prod",
      prompt_version_id: "prompt_v42",
      model_version_id: "model_gpt41mini_v8",
      environment: "production",
      deployed_by: "release-bot@acme.test",
      deployed_at: "2026-03-11T09:00:00Z",
      metadata_json: { release_channel: "progressive" },
      created_at: "2026-03-11T09:00:00Z",
    },
    prompt_version: {
      id: "prompt_v42",
      project_id: demoProject.id,
      version: "support/refund-v42",
      created_at: "2026-03-10T17:00:00Z",
      updated_at: "2026-03-10T17:00:00Z",
      label: "Refund support prompt",
      notes: "Expanded retrieval context from 4 to 6 chunks.",
    },
    model_version: {
      id: "model_gpt41mini_v8",
      project_id: demoProject.id,
      provider: "openai",
      model_name: "gpt-4.1-mini",
      model_version: "2026-03-08",
      model_family: "gpt-4.1",
      model_revision: "mini",
      route_key: "prod-stable",
      label: "Support stable",
      identity_key: "openai:gpt-4.1-mini:2026-03-08",
      created_at: "2026-03-08T12:00:00Z",
      updated_at: "2026-03-08T12:00:00Z",
    },
    time_since_deployment_minutes: 82,
  },
  guardrail_activity: [
    { policy_type: "structured_output", trigger_count: 11, last_trigger_time: "2026-03-11T10:26:00Z" },
    { policy_type: "latency_retry", trigger_count: 4, last_trigger_time: "2026-03-11T10:27:00Z" },
  ],
  possible_root_causes: [
    { pattern: "Prompt rollout expanded retrieval context from 4 to 6 chunks", type: "prompt_pattern", confidence: 0.77 },
    { pattern: "Retrieval timeout under long-context prompts", type: "retrieval_pattern", confidence: 0.71 },
  ],
  graph_related_patterns: [
    { pattern: "Retrieval timeout under long-context prompts", type: "retrieval_latency", confidence: 0.73, trace_count: 142 },
  ],
  recommended_mitigations: [
    "Enable structured output validation on the full response path",
    "Add retry policy for retrieval failures before fallback",
    "Pause rollout of prompt version support/refund-v42",
  ],
  related_regressions: [
    {
      id: "reg_demo_retrieval",
      organization_id: "org_demo",
      project_id: demoProject.id,
      metric_name: "retrieval_latency_ms",
      current_value: "980",
      baseline_value: "410",
      delta_absolute: "570",
      delta_percent: "139.0",
      scope_type: "environment",
      scope_id: "production",
      window_minutes: 30,
      detected_at: "2026-03-11T10:21:00Z",
      metadata_json: { sample_size: 128 },
    },
  ],
  recent_signals: [
    {
      event_type: "deployment_created",
      title: "Prompt v42 deployed to production",
      summary: "Progressive rollout started for the new support prompt.",
      timestamp: "2026-03-11T09:00:00Z",
      severity: "medium",
      metadata: { path: "/deployments/dep_demo_v42" },
    },
    {
      event_type: "guardrail_triggered",
      title: "Structured output retry concentration increased",
      summary: "Schema validation retried 11 requests in the last 30 minutes.",
      timestamp: "2026-03-11T10:26:00Z",
      severity: "high",
      metadata: { path: "/guardrails" },
    },
  ],
};

export const demoDeploymentDetail: DeploymentDetailRead = {
  id: "dep_demo_v42",
  project_id: demoProject.id,
  environment_id: "env_demo_prod",
  prompt_version_id: "prompt_v42",
  model_version_id: "model_gpt41mini_v8",
  environment: "production",
  deployed_by: "release-bot@acme.test",
  deployed_at: "2026-03-11T09:00:00Z",
  metadata_json: {
    rollout: "progressive 20%",
    release_reason: "refund handling improvement",
    linked_simulation: "sim_demo_v42",
  },
  created_at: "2026-03-11T09:00:00Z",
  prompt_version: demoIncidentCommand.deployment_context?.prompt_version ?? null,
  model_version: demoIncidentCommand.deployment_context?.model_version ?? null,
  events: [
    {
      id: "evt_dep_1",
      deployment_id: "dep_demo_v42",
      event_type: "created",
      metadata_json: null,
      created_at: "2026-03-11T09:00:00Z",
    },
    {
      id: "evt_dep_2",
      deployment_id: "dep_demo_v42",
      event_type: "gate_warned",
      metadata_json: null,
      created_at: "2026-03-11T09:04:00Z",
    },
  ],
  rollbacks: [],
  incident_ids: ["inc_demo_latency"],
  latest_risk_score: {
    deployment_id: "dep_demo_v42",
    risk_score: 72,
    risk_level: "high",
    analysis_json: {},
    recommendations: [
      { action: "rollback", summary: "Revert prompt v42 if p95 retrieval latency remains elevated." },
    ],
    created_at: "2026-03-11T09:05:00Z",
  },
  intelligence: {
    deployment_id: "dep_demo_v42",
    risk_score: 72,
    risk_explanations: [
      "Similar retrieval latency failures have been seen across other deployments with expanded context windows.",
      "Current rollout has insufficient retry coverage for retrieval failures.",
    ],
    graph_risk_patterns: [
      { pattern: "Retrieval timeout under long-context prompts", risk: "high", trace_count: 142 },
    ],
    recommended_guardrails: ["enable latency_retry", "enable structured_output"],
  },
  gate: {
    decision: "WARN",
    risk_score: 72,
    explanations: [
      "High regression probability in retrieval latency",
      "Similar failures seen across organizations",
      "Insufficient guardrail coverage for retrieval retries",
      "Recent incident correlation detected during rollout",
    ],
    recommended_guardrails: ["latency_retry", "structured_output"],
  },
};

export const demoGuardrailSummary = {
  policies: [
    {
      title: "Structured output policy",
      mode: "enforce",
      summary: "Schema validation catches malformed tool responses before they reach users.",
    },
    {
      title: "Latency retry policy",
      mode: "warn",
      summary: "Retrieval retry cushions transient upstream failures during traffic spikes.",
    },
  ],
};

export const demoSuggestedFix = {
  title: "Roll back prompt v42 after enabling retrieval retry",
  description:
    "The likely change vector is the prompt rollout. Restore the previous prompt, enable latency retry, then compare baseline vs failing traces before redeploying.",
};

export const pythonSnippet = `from reliai import ReliaiClient

client = ReliaiClient(api_key="reliai_...")

with client.span("ai_request"):
    response = llm.generate(prompt)`;

export const nodeSnippet = `import { ReliaiClient } from "reliai";

const client = new ReliaiClient({
  apiKey: process.env.RELIAI_KEY,
});

await client.span("ai_request", async () => {
  return llm.generate(prompt);
});`;
